# Site settings
title: Gtk-rs
description: > # this means to ignore newlines until "baseurl:"
  Rust bindings for GTK+ and GLib-based libraries
baseurl: "/gtk-rs.github.io/" # the subpath of your site, e.g. /blog/
url: "https://martinber.github.io/gtk-rs.github.io/" # the base hostname & protocol for your site
github_username: martinber
permalink: /blog/:year/:month/:day/:title.html
authors:
  gkoz: '<a href="https://github.com/gkoz">Gleb Kozyrev</a>'
  imperio: '<a href="https://github.com/GuillaumeGomez">Guillaume Gomez</a>'
exclude:
  - CNAME
  - README.md
  - "Gemfile*"
  - "*.sh"

# Build settings
markdown: kramdown
